#!/usr/bin/env bash
# Define function to display subdomain information
domain_info () {
    local domain="$1"
    local sub="$2"
    subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -n "$sub" ]; then
        subdomains=("$sub")
    fi

    for sub in "${subdomains[@]}"; do
        local result=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | tail -n1)
        local subdomain=$(awk '{split($0, DOMAIN, "."); print "The subdomain " DOMAIN[1]}' <<< "$sub.$domain")
        local record=$(awk '{print " is a " $4 " record and points to " $5}' <<< "$result")
        echo "$subdomain$record"
    done
}
domain_info "$1" "$2"
