#!/usr/bin/env bash
# Define function to display subdomain information
display_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short -t CNAME "$sub.$domain" | awk -F. '{print $2}')
        destination=$(dig +short "$sub.$domain")

        if [ -z "$record_type" ]; then
            record_type="A"
        fi

        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}
# Extract domain and subdomain (if provided)
domain="$1"
subdomain="$2"
# Call display_info function
display_info "$domain" "$subdomain"
