#!/bin/bash

domain_info() {
    subdomains=("www" "lb-01" "web-01" "web-02")

    query_domain="$1"
    query_subdomain="$2"

    perform_query() {
        local sub="$1"
        dig "$sub.$query_domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -v sub="$sub" -v dom="${query_domain%.*}" '{print "The subdomain " dom " is a " $4 " record and points to " $5}'
    }

    if [ -z "$query_subdomain" ]; then
        for sub in "${subdomains[@]}"; do
            perform_query "$sub"
        done
    else
        perform_query "$query_subdomain"
    fi
}

domain_info "$1" "$2"
