#!/usr/bin/env bash
# Define function to display subdomain information
domain_info () {
    local domain="$1"
    local subdomain="${2:-www}"
    dig_result=$(dig "$subdomain.$domain" +short | grep -A1 'ANSWER SECTION:')

    if [ -z "$dig_result" ]; then
        echo "No record found for $subdomain.$domain"
    else
        record_type=$(echo "$dig_result" | awk -F. '{print $2}')
        destination=$(echo "$dig_result")

        echo "The subdomain $subdomain is a ${record_type:-A} record and points to ${destination:-[NOT FOUND]}"
    fi
}

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
domain_info "$1" "$2"