#!/usr/bin/env bash
# transfer a file from client to server

path_to_file=$1
ip_addr=$2
usr_name=$3
ssh_key=$4
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
scp_option="-o StrictHostKeyChecking=no -i $ssh_key"
scp "$scp_option" "$path_to_file" "$usr_name"@"$ip_addr":~/
