#!/usr/bin/env bash
# installs nginx and confiures it
sudo apt update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
chown -R "$USER" /var/www/
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
