#!/usr/bin/env bash
# looks for a file and tells details about the file

filename="school"
if [ -e $filename ]
then
	echo "$filename exists"
	if [ -s $filename ]
	then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi
	if [ -f $filename ]
	then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
