#!/usr/bin/env bash
# configure nginx to run of port 8080 and as user nginx
# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    exit 1
fi

# Change nginx user in nginx.conf
sed -i 's/#user www-data/user nginx;/' /etc/nginx/nginx.conf

# Adjust permissions if necessary
chown nginx /etc/nginx/nginx.conf

# Change the listening port in the default site configuration
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
pkill apache2
# Restart nginx for changes to take effect
-u nginx service nginx restart
