#!/usr/bin/env bash
# configure nginx to run of port 8080 and as user nginx
# Check if the script is run as root
# Change nginx user in nginx.conf
chmod 644 /etc/nginx/nginx.conf
# Adjust permissions if necessary
chown nginx /etc/nginx/nginx.conf

# Change the listening port in the default site configuration
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

pkill apache2
# Restart nginx for changes to take effect
sudo -u nginx service nginx restart
