#!/usr/bin/env bash
# runs nginx as nginx
pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 600 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
